export default {
  none: 'https://tabstats.com/images/r6/ranks/?rank=&champ=0',
  copperIV: 'https://tabstats.com/images/r6/ranks/?rank=1&champ=0',
  copperIII: 'https://tabstats.com/images/r6/ranks/?rank=2&champ=0',
  copperII: 'https://tabstats.com/images/r6/ranks/?rank=3&champ=0',
  copperI: 'https://tabstats.com/images/r6/ranks/?rank=4&champ=0',
  bronzeIV: 'https://tabstats.com/images/r6/ranks/?rank=5&champ=0',
  bronzeIII: 'https://tabstats.com/images/r6/ranks/?rank=6&champ=0',
  bronzeII: 'https://tabstats.com/images/r6/ranks/?rank=7&champ=0',
  bronzeI: 'https://tabstats.com/images/r6/ranks/?rank=8&champ=0',
  silverIV: 'https://tabstats.com/images/r6/ranks/?rank=9&champ=0',
  silverIII: 'https://tabstats.com/images/r6/ranks/?rank=10&champ=0',
  silverII: 'https://tabstats.com/images/r6/ranks/?rank=11&champ=0',
  silverI: 'https://tabstats.com/images/r6/ranks/?rank=12&champ=0',
  goldIV: 'https://tabstats.com/images/r6/ranks/?rank=13&champ=0',
  goldIII: 'https://tabstats.com/images/r6/ranks/?rank=14&champ=0',
  goldII: 'https://tabstats.com/images/r6/ranks/?rank=15&champ=0',
  goldI: 'https://tabstats.com/images/r6/ranks/?rank=16&champ=0',
  platinumIII: 'https://tabstats.com/images/r6/ranks/?rank=17&champ=0',
  platinumII: 'https://tabstats.com/images/r6/ranks/?rank=18&champ=0',
  platinumI: 'https://tabstats.com/images/r6/ranks/?rank=19&champ=0',
  diamond: 'https://tabstats.com/images/r6/ranks/?rank=20&champ=0',
  champions: 'https://tabstats.com/images/r6/ranks/?rank=21&champ=0',
};
